-- Fix admin password hash (generated by Spring BCryptPasswordEncoder)
-- Password: admin123456
UPDATE users
SET password = '$2a$10$OIX5H1j2A3fxJj7Pw3rxTOn15xUN55Kra766/nLAvALhUoDFb35VK'
WHERE email = 'admin@hafsahsplace.com';
